os: linux
dist: trusty
sudo: false
language: python
python: "3.6"

before_install:
    - pip install conan
      && conan config install https://vuo.org/sites/default/files/conan-linux.zip

install:
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm freeframe/*
